# Site settings
title: argmin gravitas
fmtTitle: argmin gravitas
email: g@gleech.org  
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://effortless-bombolone-68cc17.netlify.app
github_username:  g-leech
highlighter: none

# Build settings
markdown: kramdown
