use anyhow::{Context, Result};
use chrono::Local;
use std::fs;
use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, Stdio};

use crate::config;

/// (post_url, dead_url, archive_url)
pub type DeadItem = (String, String, String);

/// Desktop notification via libnotify's `notify-send`.
///   install: `sudo apt install libnotify-bin`
/// Needs a running notification daemon on the session D-Bus. Under a headless
/// 3 AM `systemd --user` job with no graphical session this will fail — that's
/// fine, the caller wraps it in `if let Err(..) { warn }` and carries on.
pub fn desktop_notification(title: &str, message: &str) -> Result<()> {
    let status = Command::new("notify-send")
        .arg("--app-name=archiver")
        // Best-effort sound; honoured only by daemons that implement the
        // freedesktop sound-name spec (GNOME does, some others don't).
        .arg("--hint=string:sound-name:message-new-instant")
        .arg(title)
        .arg(message)
        .status()
        .context("spawn notify-send (install: apt install libnotify-bin)")?;
    if !status.success() {
        anyhow::bail!("notify-send exited with {}", status);
    }
    Ok(())
}

/// Send mail by piping an RFC-5322 message to a `sendmail`-compatible MTA.
///
/// Mirrors the original Mail.app design decision: the app holds NO credentials.
/// On Linux the conventional zero-fuss MTA is msmtp:
///   sudo apt install msmtp msmtp-mta      # provides /usr/sbin/sendmail
/// then put your SMTP account in ~/.msmtprc, e.g.:
///   account default
///   host smtp.gmail.com
///   port 587
///   tls on
///   auth on
///   user you@gmail.com
///   passwordeval "pass show gmail"   # or an app-password, kept out of the repo
///   from you@gmail.com
///
/// `notify_email` is used for both From and To (margot mails herself), so this
/// needs no new config fields. msmtp supplies the envelope-from from ~/.msmtprc.
pub fn send_mail(to: &str, subject: &str, body: &str) -> Result<()> {
    // CRLF line endings + a UTF-8 content-type header so the 🐾 in the body
    // survives. `sendmail -t` reads recipients from the To: header.
    let msg = format!(
        "From: archiver <{to}>\r\n\
         To: {to}\r\n\
         Subject: {subject}\r\n\
         MIME-Version: 1.0\r\n\
         Content-Type: text/plain; charset=utf-8\r\n\
         \r\n\
         {body}"
    );
    let mut child = Command::new("sendmail")
        .arg("-t") // recipients come from the headers
        .arg("-oi") // a lone "." in the body is not end-of-message
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
        .context(
            "spawn sendmail — install an MTA: `apt install msmtp msmtp-mta`. \
             (If running under systemd --user and it's 'not found', the unit's \
             PATH may lack /usr/sbin; set Environment=PATH=/usr/sbin:/usr/bin:/bin \
             or call /usr/sbin/sendmail directly.)",
        )?;
    child
        .stdin
        .take()
        .context("sendmail stdin unavailable")?
        .write_all(msg.as_bytes())
        .context("write message to sendmail")?;
    let out = child.wait_with_output()?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        anyhow::bail!("sendmail failed: {}", stderr.trim());
    }
    Ok(())
}

/// Appends a dated section to SUBSTACK_DEAD_LINKS.md at the repo root.
/// Returns the path written if anything was appended.
pub fn append_substack_todo(items: &[DeadItem]) -> Result<Option<PathBuf>> {
    if items.is_empty() {
        return Ok(None);
    }
    let path = config::repo_root().join("SUBSTACK_DEAD_LINKS.md");
    let mut content = if path.exists() {
        fs::read_to_string(&path).unwrap_or_default()
    } else {
        String::from(
            "# Substack dead links\n\n\
             Generated by `archiver maintain`. Local archives are already published on \
             croissanthology.com — these are the substack posts that still need manual \
             link patches. Tick the box once you've updated the substack post.\n\n",
        )
    };
    if !content.ends_with('\n') {
        content.push('\n');
    }
    content.push_str(&format!("## {}\n\n", Local::now().format("%Y-%m-%d")));
    for (post, dead, archive) in items {
        content.push_str(&format!(
            "- [ ] **{}**\n  - dead: `{}`\n  - archive: <{}>\n\n",
            post, dead, archive
        ));
    }
    fs::write(&path, content)?;
    Ok(Some(path))
}

pub fn render_mail_body(items: &[DeadItem]) -> String {
    let mut body = String::from(
        "hi margot — these substack posts cite links that have gone dead.\n\
         local archives are already live on croissanthology.com.\n\
         update substack manually when you get a sec.\n\n",
    );
    for (post, dead, archive) in items {
        body.push_str(&format!(
            "post:    {}\ndead:    {}\narchive: {}\n\n",
            post, dead, archive
        ));
    }
    body.push_str("— archiver 🐾\n");
    body
}

pub fn terminal_bell() {
    print!("\x07");
}
