FROM jekyll/jekyll:4.1.0

# Update RubyGems.
# RUN gem update --system 3.3.22

# Install bundler if it’s not already available.
RUN gem install bundler

# Create a working directory.
WORKDIR /srv/jekyll

# Copy dependency files first for caching.
COPY Gemfile Gemfile.lock ./

# Update the bundle and add the current platform lock.
RUN bundle update
# RUN bundle lock --add-platform x86_64-linux-musl
