FROM jekyll/jekyll:3.8.6

# Create a working directory.
WORKDIR /srv/jekyll

# Copy dependency files first for caching.
COPY Gemfile ./

# Make files be owned by jekyll user.
RUN chown -R jekyll:jekyll /srv/jekyll

# Update the bundle and add the current platform lock.
RUN bundle lock

