FROM jekyll/jekyll:3.8.6

# Update RubyGems.

# Install bundler if it’s not already available.
# RUN gem install bundler

# Create a working directory.
WORKDIR /srv/jekyll

# Copy dependency files first for caching.
COPY Gemfile ./

RUN chown -R jekyll:jekyll /srv/jekyll

# Update the bundle and add the current platform lock.
RUN bundle lock

