# Base on alpine
FROM alpine:latest

# Install ImageMagick and any required utilities (find)
RUN apk update && apk add --no-cache \
imagemagick \
imagemagick-dev \
libjpeg-turbo-dev \
libpng-dev \
libwebp-dev \
tiff-dev \
findutils \
&& rm -rf /var/cache/apk/*

# Set the working directory to the mounted volume
WORKDIR /srv

COPY ./Dockerfiles/imagemagick/mogrify.sh /app/mogrify.sh

# The image simply runs a shell command passed via arguments
ENTRYPOINT ["/app/mogrify.sh"]