#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

rm -r _site
rm -r .jekyll-cache
WC=$(find . -type f ! -path "./img/*" ! -path "./.git/*" ! -path "./rotproofLinks/*" ! -path "./files/*" ! -path "./.jekyll-cache/*" -exec wc -w {} + | tail -n1 | awk '{print $1;}')
tweetwords=120000 # as of Jan 2025
echo "{{" $(($WC + $tweetwords)) "| thousands_separated }}" > _includes/wc.html
git add _includes/wc.html
