name: Deploy to Cloudflare Manually

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and deploy"
        required: true
        default: "master"
      environment:
        description: "Environment to deploy to"
        required: true
        default: "development"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-cloudflare.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
