name: Deploy to Netlify Manually

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and deploy"
        required: true
        default: "master"
      environment:
        description: "Environment to deploy to"
        required: true
        default: "development"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-netlify.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      environment: ${{ github.event.inputs.environment }}
