name: Deploy to Neflify on Push

on:
  push:
    branches:
      - master

jobs:
  deploy_master:
    if: ${{ github.ref_name == 'master' }}
    uses: ./.github/workflows/deploy-netlify.yml
    environment: production
    secrets: inherit
    with:
      branch: master

  deploy_non_master:
    if: ${{ github.ref_name != 'master' }}
    uses: ./.github/workflows/deploy-netlify.yml
    environment: development
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}
