name: Deploy to Neflify on Push

on:
  push:
    branches:
      - master

jobs:
  deploy_master:
    if: ${{ github.ref_name == 'master' }}
    uses: ./.github/workflows/deploy-netlify.yml
    secrets: inherit
    with:
      branch: master
      environment: production

  deploy_non_master:
    if: ${{ github.ref_name != 'master' }}
    uses: ./.github/workflows/deploy-netlify.yml
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}
      environment: development
