name: Build & Deploy to Cloudflare

on:
  # 1. Manual trigger via the Actions tab
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloudflare
    runs-on: ubuntu-latest
    
    # 2. Set job-level environment for secrets access.
    environment: ${{ inputs.environment }}

    steps:
      # 3. Check out the specified branch
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      # 4. Build the site using your existing Docker build script
      - name: Build the site using Docker
        run: |
          ./scripts/build.sh

      # 5. Deploy to Cloudflare using the Cloudflare Wrangler Action
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: ${{ github.event.inputs.environment }}
          workingDirectory: "_site"
