name: Build & Deploy to Netlify

on:
  # 1. Workflow call invoked by another action
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build-and-deploy:
    name: Build and Deploy to Netlify
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      # 2. Validate our secrets are present
      - name: Check secrets
        run: |
          if [ -z "${{ secrets.NETLIFY_AUTH_TOKEN }}" ]; then
            echo "NETLIFY_AUTH_TOKEN is NOT set"
            exit 1
          else
            echo "NETLIFY_AUTH_TOKEN is set"
          fi
          if [ -z "${{ secrets.NETLIFY_SITE_ID }}" ]; then
            echo "NETLIFY_SITE_ID is NOT set"
            exit 1
          else
            echo "NETLIFY_SITE_ID is set"
          fi

      # 3. Check out the specified branch
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      # 4. Build the site using your existing Docker build script
      - name: Build the site using Docker
        run: |
          ./scripts/build.sh

      # 5. Deploy to Netlify using the Netlify CLI Action
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          # --prod does a production deploy
          args: deploy --dir=_site --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
