name: Deploy to Neflify on Push

on:
  push:
    branches:
      - master

jobs:
  deploy_master:
    if: ${{ github.ref_name == 'master' }}
    uses: ./.github/workflows/deploy-netlify.yml
    with:
      environment: production
      branch: master

  deploy_non_master:
    if: ${{ github.ref_name != 'master' }}
    uses: ./.github/workflows/deploy-netlify.yml
    with:
      environment: development
      branch: ${{ github.ref_name }}
